# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate
#       Stop all: docker-compose down (add -v to wipe db)
#
version: '3.7'

volumes:
  db_data:

services:
  app:
    image: himawari
    container_name: himawari
    restart: unless-stopped
    build:
      context: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      DATABASE_HOST: db
      DATABASE_PORT: 5435
      DATABASE_NAME: HimawariDB
      DATABASE_USERNAME: HimawariUser
      DATABASE_PASSWORD: 12345678
    depends_on:
      - db
    ports:
      - '0.0.0.0:8083:8083'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8083"]
  db:
    image: postgres:14-alpine
    container_name: himawari_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: HimawariUser
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: HimawariDB
    expose:
      - 5435
    ports:
      - '5435:5435'

  pgbackups:
    container_name: himawari_pgbackups
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ~/himawari_db_backups:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      DATABASE_PORT: 5435
      POSTGRES_DB: HimawariDB
      POSTGRES_USER: HimawariUser
      POSTGRES_PASSWORD: 12345678
      SCHEDULE: "@hourly"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 2
      BACKUP_KEEP_MONTHS: 1
